---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-viewer-deployment
  namespace: shabad-os
  labels:
    app: database-viewer
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-viewer
  template:
    metadata:
      labels:
        app: database-viewer
    spec:
      containers:
      - image: shabados/database-viewer-frontend:5942a93ab4d0f7a922a032370686a1bd2dde9c0e
        name: database-viewer-frontend
        ports:
        - containerPort: 52526
          name: http
      - image: shabados/database-viewer-backend:578ab7eec4f4e0e43e3dc4caab0644941d06d911
        name: database-viewer-backend
        command: ["npm", "run", "start:production"]
        env:
        - name: PORT
          value: "52526"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/auth/google/credentials.json
        volumeMounts:
        - mountPath: /var/auth/google
          name: google-application-credentials
        ports:
        - containerPort: 80
          name: http
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: database-viewer-service
  namespace: shabad-os
spec:
  selector:
    app: database-viewer
  ports:
  - name: backend
    port: 52526
    targetPort: 52526
  - name: frontend
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: database-viewer-ingress
  namespace: shabad-os
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: viewer.shabados.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: database-viewer-service
          servicePort: backend
      - path: /
        backend:
          serviceName: database-viewer-service
          servicePort: frontend
