---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-viewer-deployment--next
  namespace: shabad-os
  labels:
    app: database-viewer--next
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.database-viewer--next: regexp:^(v\d*\.\d*\.\d*-next\.\d*)$
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-viewer--next
  template:
    metadata:
      labels:
        app: database-viewer--next
    spec:
      containers:
      - image: ghcr.io/shabados/database-viewer-frontend:v1.5.1-next.0
        name: database-viewer-frontend--next
        ports:
        - containerPort: 52526
          name: http
      - image: ghcr.io/shabados/database-viewer-backend:v1.5.1-next.0
        name: database-viewer-backend--next
        command: ["npm", "run", "start:production"]
        env:
        - name: PORT
          value: "52526"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/auth/google/credentials.json
        volumeMounts:
        - mountPath: /var/auth/google
          name: google-application-credentials
        ports:
        - containerPort: 80
          name: http
      volumes:
      - name: google-application-credentials
        secret:
          secretName: google-application-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: database-viewer-service--next
  namespace: shabad-os
spec:
  selector:
    app: database-viewer--next
  ports:
  - name: backend
    port: 52526
    targetPort: 52526
  - name: frontend
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: database-viewer-ingress--next
  namespace: shabad-os
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: viewer.next.shabados.com
    http:
      paths:
      - path: /api
        backend:
          serviceName: database-viewer-service--next
          servicePort: backend
      - path: /
        backend:
          serviceName: database-viewer-service--next
          servicePort: frontend
