---
apiVersion: v1
data:
  knexfile.js: "const config = {\n  client: 'mysql',\n  connection: {\n    host: 'database-service.shabad-os',\n\
    \    user: 'shabados',\n    database: 'shabados',\n  },\n  useNullAsDefault: true,\n\
    }\n\nmodule.exports = config\n"
kind: ConfigMap
metadata:
  name: api-config--dev
  namespace: gurbani-now
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment--dev
  namespace: gurbani-now
  labels:
    app: api--dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api--dev
  template:
    metadata:
      labels:
        app: api--dev
    spec:
      containers:
      - image: gurbaninow/api-dev:a0d8392e08fdc7545fed7f44e89ed82a2254852e
        name: api-backend--dev
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: PORT
          value: "80"
        - name: KNEXFILE
          value: "/etc/config/knexfile.js"
        ports:
        - containerPort: 80
          name: http
      volumes:
      - name: config-volume
        configMap:
          name: api-config--dev
---
apiVersion: v1
kind: Service
metadata:
  name: api-service--dev
  namespace: gurbani-now
spec:
  selector:
    app: api--dev
  ports:
  - name: backend
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api--dev
  namespace: gurbani-now
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: dev-api.gurbaninow.com
    http:
      paths:
      - path: /
        backend:
          serviceName: api-service--dev
          servicePort: backend
  tls:
  - secretName: gurbaninow-tls-cert
